// frameworksday/vue/src/components/List.vue
<template>
    <div>
        <ul v-for="user in users">
            <li>{{user.fullName}}</li>
        </ul>
    </div>
</template>

<script>
  export default {
    name: 'List',
    props: {
      users: Array,
    },
    mounted() {
      console.log(this);
    },
  };
</script>

<style scoped>

</style>

// frameworksday/react_/src/components/list.js
import React from 'react';

export const ListEasyCode = props => {
  const {
    users,
  } = props;

  return (
    <ul>
      {users.map(user => {
        return <li>{user.fullName}</li>;
      })}
    </ul>
  );
};

// export class ListEasyCode extends React.Component {
//
//   renderUsers() {
//     const {
//       users,
//     } = this.props;
//
//     return users.map(user => {
//       return <li>{user.fullName}</li>;
//     })
//   }
//
//   render() {
//     const {
//       users,
//     } = this.props;
//
//     console.log(users);
//     return (
//       <ul>
//         {this.renderUsers()}
//       </ul>
//     );
//   }
// }
